blank_issues_enabled: false

contact_links:
  - name: Ask an question / advise on using reveal
    url: https://github.com/khulnasoft-labs/reveal/discussions/categories/q-a
    about: Ask a question or request support for using reveal

  - name: Share idea / feature to discuss for reveal
    url: https://github.com/khulnasoft-labs/reveal/discussions/categories/ideas
    about: Share idea / feature to discuss for reveal

  - name: Connect with PD Team (Discord)
    url: https://discord.gg/khulnasoft-labs
    about: Connect with PD Team for direct communication